FROM node:22.17.0-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml* ./
RUN pnpm i

# We don't COPY the rest because it will be mounted as a volume

EXPOSE 3000
ENV PORT 3000

CMD ["pnpm", "dev"]
