services:
  blog-payload-blue:
    container_name: blog-payload-blue
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@blog-db:27017/${MONGO_DB}?authSource=admin
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
    depends_on:
      blog-db:
        condition: service_healthy
    networks:
      - blog-net
    restart: always
    volumes:
      - ./media:/app/media
    profiles:
      - blue

  blog-payload-green:
    container_name: blog-payload-green
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@blog-db:27017/${MONGO_DB}?authSource=admin
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
    depends_on:
      blog-db:
        condition: service_healthy
    networks:
      - blog-net
    restart: always
    volumes:
      - ./media:/app/media
    profiles:
      - green


  blog-db:
    container_name: blog-db
    image: mongo:7.0
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blog-net
    restart: always

  blog-nginx:
    image: nginx:stable-alpine
    container_name: blog-nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./media:/app/media:ro
    networks:
      - blog-net
      - cloudflare-net
    restart: always

  blog-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: blog-cloudflared
    env_file:
      - .env
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - cloudflare-net
    restart: unless-stopped

networks:
  blog-net:
    driver: bridge
  cloudflare-net:
    driver: bridge

volumes:
  mongo_data:
  media-data:
